---
pid: tmp/pids/thin.pid
#socket: /tmp/thin.sock
log: log/thin.log
max_conns: 1024
timeout: 30
rackup: /usr/local/analyzethis/config.ru
environment: production
max_persistent_conns: 512
daemonize: true
servers: 2
port: 3000
